[project]
name = "living-call"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.call-access]
path = "contracts/call-access.clar"
depends_on = []

[contracts.call-core]
path = "contracts/call-core.clar"
depends_on = []

[contracts.call-integrity]
path = "contracts/call-integrity.clar"
depends_on = []

[contracts.call-metadata]
path = "contracts/call-metadata.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
